FROM bde2020/spark-worker:3.0.0-hadoop3.2

USER root
RUN apk add --no-cache build-base python3-dev
RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel \
 && python3 -m pip install --no-cache-dir happybase requests

USER root
